"""opportunity rejection_note

Revision ID: 3d13edeaa49c
Revises: e01d0c4b1260
Create Date: 2026-08-25 08:22:58.598689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d13edeaa49c'
down_revision: Union[str, None] = 'e01d0c4b1260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('rejection_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'rejection_note')
    # ### end Alembic commands ###