"""opportunity cluster_id nullable

Revision ID: 513706e4d731
Revises: 3d13edeaa49c
Create Date: 2026-08-25 13:47:07.775043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513706e4d731'
down_revision: Union[str, None] = '3d13edeaa49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('opportunities', 'cluster_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('opportunities', 'cluster_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###