"""trend_metric cluster_id nullable

Revision ID: 5b90bf393966
Revises: 954b622e7cdb
Create Date: 2026-08-29 15:28:08.991446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b90bf393966'
down_revision: Union[str, None] = '954b622e7cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trend_metrics', 'cluster_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trend_metrics', 'cluster_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###