"""cluster and opportunity source_count

Revision ID: 954b622e7cdb
Revises: 513706e4d731
Create Date: 2026-08-29 12:14:50.948769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954b622e7cdb'
down_revision: Union[str, None] = '513706e4d731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='0'：表内已有数据，NOT NULL 列必须带默认值才能 ADD
    op.add_column('demand_clusters', sa.Column('source_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('opportunities', sa.Column('source_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'source_count')
    op.drop_column('demand_clusters', 'source_count')
    # ### end Alembic commands ###