"""add signal cluster_id

Revision ID: e01d0c4b1260
Revises: 4d81458701d7
Create Date: 2026-08-22 12:10:57.747871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e01d0c4b1260'
down_revision: Union[str, None] = '4d81458701d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demand_signals', sa.Column('cluster_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'demand_signals', 'demand_clusters', ['cluster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'demand_signals', type_='foreignkey')
    op.drop_column('demand_signals', 'cluster_id')
    # ### end Alembic commands ###